version: '3.8'

services:
  # Banco de dados MySQL
  mysql:
    image: mysql:8.0
    container_name: techperifericos-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: techperifericos
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - techperifericos-network

  # API Backend
  api:
    build: .
    container_name: techperifericos-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: techperifericos
      DB_USER: appuser
      DB_PASSWORD: apppassword
      JWT_SECRET: your_super_secret_jwt_key_here_change_in_production
      JWT_EXPIRES_IN: 7d
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - ./uploads:/app/uploads
    networks:
      - techperifericos-network

  # Nginx (opcional - para proxy reverso)
  nginx:
    image: nginx:alpine
    container_name: techperifericos-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - api
    networks:
      - techperifericos-network

volumes:
  mysql_data:

networks:
  techperifericos-network:
    driver: bridge


